Reverting back to original statement syntax

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -70,13 +70,17 @@ jobs:
       run: helm test $GITHUB_HEAD_REF-$SHORT_SHA --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID
 
     - name: Delete the chart
+      if: ${{ always() }}
       run: |
-        if helm status $GITHUB_HEAD_REF-$SHORT_SHA --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID &> /dev/null;
+        if [ $ (helm status $GITHUB_HEAD_REF-$SHORT_SHA --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID | grep "STATUS: deployed" | wc -l) -ne 0 ]
         then
           helm delete $GITHUB_HEAD_REF-$SHORT_SHA --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID
-      if: ${{ always() }}
+        else
+          echo "Error: release not found"
+          exit 1
 
     - name: Delete the namespace
+      if: ${{ always() }}
       run: |
         if [ $(kubectl get namespaces -A | grep "$ACTOR_LOWERCASE-$GITHUB_RUN_ID " | wc -l) -ne 0 ]
         then
